# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0002_auto_20170902_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='account_type',
            field=models.CharField(choices=[(1, 'Patient'), (2, 'Doctor')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
