# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0003_account_info_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_info',
            name='account_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=10),
        ),
    ]
