# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0006_auto_20170903_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
