# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0007_datetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(max_length=50),
        ),
    ]
