# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0008_auto_20170903_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='date',
            field=models.DateField(max_length=10),
        ),
    ]
