# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0009_auto_20170903_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=50)),
                ('patient', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=50)),
                ('starttime', models.CharField(max_length=10)),
                ('endtime', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='DateText',
        ),
    ]
