# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0010_auto_20170903_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=20)),
                ('date', models.DateField(max_length=20)),
                ('starttime', models.TimeField(max_length=10)),
                ('endtime', models.TimeField(max_length=10)),
            ],
        ),
    ]
