# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0011_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_info',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Male', 'Female')], max_length=6),
        ),
    ]
