# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0012_auto_20170904_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='endtime',
            field=models.TimeField(max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='starttime',
            field=models.TimeField(max_length=10),
        ),
        migrations.AlterField(
            model_name='requests',
            name='endtime',
            field=models.TimeField(max_length=10),
        ),
        migrations.AlterField(
            model_name='requests',
            name='starttime',
            field=models.TimeField(max_length=10),
        ),
    ]
