# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0014_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.DateTimeField(auto_now=True)),
                ('logout', models.DateTimeField(auto_now=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.Accounts')),
            ],
        ),
    ]
