# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0017_auto_20170905_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
