# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0020_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='latest_logout',
            field=models.DateTimeField(default='2017-09-29 10:00:00'),
            preserve_default=False,
        ),
    ]
