# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0021_accounts_latest_logout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginRecord',
        ),
        migrations.DeleteModel(
            name='Parking',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
